version: 2
jobs:
  build:
    docker:
      - image: node:8
      - image: circleci/mongo:3.6
    environment:
      - NODE_ENV: test
      - PORT: 3006
      - NJORD_API_TOKEN: fake
      - DB_CONNECTION_STRING: mongodb://localhost:27017/njord
      - DB_TEST_CONNECTION_STRING: mongodb://localhost:27017/njord-test
      - NJORD_HOSTNAME: http://localhost:3006
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: yarn test

  deploy:
    docker:
      - image: node:8
    steps:
      - checkout
      - run:
        name: Publish Njord on NPM
        command: ./node_modules/.bin/publish
      - run:
        name: Push changelog update to Slack
        command: ./node_modules/.bin/push-changelog-update

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
