version: 2.0
jobs:
  checkout:
    working_directory: ~/project
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-
      - run:
          name: Install Dependencies
          command: ls && yarn install
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: .
          paths:
            - ./*
            - node_modules

  test:
    working_directory: ~/project
    docker:
      - image: node:8
      - image: circleci/mongo:3.6
    environment:
      - NODE_ENV: test
      - PORT: 3006
      - NJORD_API_TOKEN: fake
      - DB_CONNECTION_STRING: mongodb://localhost:27017/njord
      - DB_TEST_CONNECTION_STRING: mongodb://localhost:27017/njord-test
      - NJORD_URL: http://localhost:3006
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Run Tests
          command: yarn test

  build:
    working_directory: ~/project
    docker:
      - image: node:8
      - image: circleci/mongo:3.6
    environment:
      - NODE_ENV: test
      - PORT: 3006
      - NJORD_API_TOKEN: fake
      - DB_CONNECTION_STRING: mongodb://localhost:27017/njord
      - DB_TEST_CONNECTION_STRING: mongodb://localhost:27017/njord-test
      - NJORD_URL: http://localhost:3006
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Checks if it can Build
          command: yarn build
      - persist_to_workspace:
          root: ~/project
          paths:
            - build/* 

  deploy:
    docker:
      - image: node:8
    steps:
      - checkout
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-
      - run: yarn install
      - save_cache:
          key: v2-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Publish Njord on NPM
          command: ./node_modules/.bin/publish
      - run:
          name: Push changelog update to Slack
          command: ./node_modules/.bin/push-changelog-update

workflows:
  version: 2
  test:
    jobs:
      - checkout
      - build:
          requires:
            - checkout
      - test:
          requires:
            - checkout
            - build
      - deploy:
          requires:
            - build
            - checkout
            - test
          filters:
            branches:
              only: master
